x-php-rust: &php-rust
  build: .
  entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
  volumes:
    - .:/app
    - cargo-registry:/root/.cargo/registry
    - cargo-git:/root/.cargo/git
    - target:/app/target
  working_dir: /app

services:
  php-rust:
    <<: *php-rust
    command: bash

  run-tests:
    <<: *php-rust
    command: make test

  run-examples:
    <<: *php-rust
    command: make examples

  run-checks:
    <<: *php-rust
    command: bash packaging/docker/run-dev-checks.sh

volumes:
  cargo-registry:
  cargo-git:
  target:
